name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install server dependencies
        run: npm install
        working-directory: server
      - name: Lint
        run: npm run lint
      - name: Frontend tests
        run: npm run test -- --run
